### ISSUE TITLE
curves is not visible from py_pkg, np is visible from curves

### ISSUE THREAD

**Issue by endolith** [AlexIoannides/py-package-template#18]
Is this the intended behavior?  I'm trying to learn the "Right" way to cleanly structure packages and imports.

If I do:

```
In [1]: import py_pkg

In [2]: py_pkg.
```
and then press Tab, there is no auto-completion for `curves` or anything else.  I would expect to be able to see what is available.

On the other hand, if I do

```
In [3]: from py_pkg import curves

In [4]: curves.
```
and press Tab, it shows irrelevant things like `np`, `abc`, `Dict`, `Tuple` etc. that are imported into `curves.py` but are not part of this `py_package_template` package.  Is that intentional?  I would expect those sorts of imports to be hidden, and only things like `DemandMonotonicityError` and `PriceRanges` to show up.

**Comment by AlexIoannides** [comment]
Looks okay to me:

<img width="1300" alt="image" src="https://github.com/AlexIoannides/py-package-template/assets/5968486/1c03e9de-f915-411e-a38c-e0028ec673c0">

The "irrelevant things" are there because they are imported within `curves.py`. The only way to get rid of them would be to define `__all__ = [...]` at the top of the module.
